import { Icons } from "@/components/shared/Icons";
import { Category, type CategoryIcon } from "@/types";

export const categories: string[] = [
	"All",
	"Apparels",
	"Streaming",
	"Programming",
	"Social",
	"Gaming",
	"Food",
	"Technology",
	"Others",
];

export const iconsByCategory: CategoryIcon[] = [
	{
		category: Category.Apparels,
		icons: [Icons.adidas, Icons.nike, Icons.puma, Icons.reebok, Icons.uniqlo, Icons.handm, Icons.zara],
	},
	{
		category: Category.Streaming,
		icons: [
			Icons.netflix,
			Icons.amazonPrime,
			Icons.twitch,
			Icons.youtube,
			Icons.appleMusic,
			Icons.spotify,
			Icons.amazonMusic,
		],
	},
	{
		category: Category.Programming,
		icons: [
			Icons.npm,
			Icons.react,
			Icons.tailwind,
			Icons.typescript,
			Icons.next,
			Icons.node,
			Icons.express,
			Icons.dotenv,
			Icons.dotnet,
			Icons.assemblyScript,
			Icons.astro,
			Icons.auth0,
			Icons.axios,
			Icons.babel,
			Icons.c,
			Icons.cPlusPlus,
			Icons.npm,
			Icons.react,
			Icons.tailwind,
			Icons.typescript,
			Icons.next,
			Icons.node,
			Icons.express,
			Icons.dotenv,
			Icons.dotnet,
			Icons.assemblyScript,
			Icons.astro,
			Icons.auth0,
			Icons.axios,
			Icons.babel,
			Icons.c,
			Icons.cPlusPlus,
			Icons.npm,
			Icons.react,
			Icons.tailwind,
			Icons.typescript,
			Icons.next,
			Icons.node,
			Icons.express,
			Icons.dotenv,
			Icons.dotnet,
			Icons.assemblyScript,
			Icons.astro,
			Icons.auth0,
			Icons.axios,
			Icons.babel,
			Icons.c,
			Icons.cPlusPlus,
			Icons.npm,
			Icons.react,
			Icons.tailwind,
			Icons.typescript,
			Icons.next,
			Icons.node,
			Icons.express,
			Icons.dotenv,
			Icons.dotnet,
			Icons.assemblyScript,
			Icons.astro,
			Icons.auth0,
			Icons.axios,
			Icons.babel,
			Icons.c,
			Icons.cPlusPlus,
		],
	},
];
